### ISSUE TITLE
Easy way to link to an arbitrary register

### ISSUE THREAD

**Issue by cseickel** [ojroques/nvim-osc52#1]
With the old version, I had this autocmd:

```
    autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is 'c' | execute 'OSCYankReg c' | endif
```

Which just made the "c" register my system clipboard. I use that along with remapped Control-c and Control-v so that those standard shortcuts copy to the local system when I want that but my "unnamed" register is used normally.

```
" Use Ctl+c/x/v as secondary clipboard
nnoremap <silent> <C-c> "cy
vnoremap <silent> <C-c> "cy
inoremap <silent> <C-c> <C-o>"cyiw

inoremap <silent> <C-x> <C-o>"cdiw
vnoremap <silent> <C-x> "cd
nnoremap <silent> <C-x> "cdiw

nnoremap <silent> <C-v> "cp
vnoremap <silent> <C-v> "cp
inoremap <silent> <C-v> <C-o>"cp
tnoremap <silent> <C-v> <c-\><c-n>"cpa
```

Can you tell me the equivalent setting in the new version?

**Comment by ojroques** [comment]
Hello!

You have two options:
1. Set the clipboard provider of Neovim to use the plugin, see the instructions [here](https://github.com/ojroques/nvim-osc52#using-nvim-osc52-as-clipboard-provider). Basically it tells Neovim that your "+" register should now call the plugin. The most natural solution in my opinion but you'd need to change your mappings to use the "+" register.
2. Keep your autocmd but call this function instead: https://github.com/ojroques/nvim-osc52/blob/99fcb75bcde8ab2e7051bc9e058f2a6d452c4781/lua/osc52.lua#L79 with 'c' as argument. So something like (using the new API for autocmd):
```lua
function copy()
  if vim.v.event.operator == 'y' and vim.v.event.regname == 'c' then
    require('osc52').copy_register('c')
  end
end

vim.api.nvim_create_autocmd('TextYankPost', {callback = copy})
```

**Comment by cseickel** [comment]
Thanks! The second option is exactly what I was looking for. I like it that way because I liked having an easy to use second register (Control-c/x/v) and I didn't want to oscyank every time. Now that i think about more though, maybe using the plus register for that makes more sense, and I can just not copy to plus with the unnamed register.

Either way, thanks for the help and the **incredibly** useful plugin!

**Comment by ojroques** [comment]
Glad you find it useful!
