### ISSUE TITLE
osc52.copy_visual is copying one more character than selected

### ISSUE THREAD

**Issue by shmerl** [ojroques/nvim-osc52#10]
I just tried nvim + osc52 plugin in patched konsole with OSC52 support (Linux, KDE Plasma) and there a problem with visual selection function.

Basically, when selecting some piece of text, the plugin copies that plus an additional character after that. And if that selection runs intil the end of the line for example, that will include `\n`.

It even reports N+1 characters copied when I selected only N (just checked).

Here is my configuration for it:

```
" OSC-52 clipboard handling
lua <<EOF
osc52 = require('osc52')

osc52 .setup { 
  silent = false
}

vim.keymap.set('x', '<C-c>', osc52.copy_visual)
EOF
```

The way I'm using it - in visual mode select something, then press Ctrl+C. It copes things, but as above, there is that length problem.

**Comment by shmerl** [comment]
Btw, I just tested vim-oscyank and it doesn't have that issue!

The way I mapped it there:

```
xnoremap <C-c> :OSCYank<CR>
```

**Comment by ojroques** [comment]
Does it happen with konsole only? Also, what is the value of your `selection` option (`:set selection?`)?

**Comment by shmerl** [comment]
`:set selection` shows `selection=exclusive`.

Here is my config:

```
set selection=exclusive
set virtualedit=block,onemore
```

I think I tried it in kitty, but there it's even more broken overall, so I didn't dig much into that.

May be `virtualedit` setting affects it?

**Comment by ojroques** [comment]
On my side it works as expected with your settings. Can you try with `set selection=inclusive` and see if it works?

**Comment by shmerl** [comment]
With inclusive it actually works correctly.

So I think what happens, with exclusive it ignores the selection length and copies from the beginning of the selection to the current position of the cursor including it, even though the latter isn't selected (becasue of exclusive setting). So that produces one character more than needed.

**Comment by shmerl** [comment]
I see the code doing this:

```
  -- Retrieve text
  vim.go.clipboard = ''
  vim.go.selection = 'inclusive'
  local command = fmt('keepjumps normal! %s', commands[mode][type])
  vim.cmd(fmt('silent execute "%s"', command))
  local text = vim.fn.getreg('"')

  -- Restore user settings
  vim.go.clipboard = clipboard
  vim.go.selection = selection
```

This looks like it ignores it whether selection setting was exclusive and treats everything as inclusive?

**Comment by shmerl** [comment]
Yeah, just confirmed it. Commenting out `vim.go.selection = 'inclusive'` makes it work correctly for me!

So I think the code should make a distinction whether selection was exclusive or not with some check.
