### ISSUE TITLE
Copying gets broken on long text

### ISSUE THREAD

**Issue by shmerl** [ojroques/nvim-osc52#11]
I was testing nvim-osc52 with nvim (0.7.2) and patched konsole with with osc52 support, and noticed that copying gets truncated on certain input (konsole patch [here](https://invent.kde.org/utilities/konsole/-/merge_requests/767)).

For example, copying [osc52.lua](https://raw.githubusercontent.com/ojroques/nvim-osc52/main/lua/osc52.lua) itself from the source code, produces only this when pasting:

```
-------------------- VARIABLES -----------------------------
local base64 = require('base64')
local fmt = string.format
local commands = {
  operator = {block = "`[\\<C-v>`]y", char = "`[
```

I'm not sure if it's an issue with plugin or with konsole's handling of osc52.

**Comment by muesli** [comment]
Author of the konsole patch here, and I'm pretty sure this issue has nothing to do with the way nvim-osc52 works, but with konsole's internal buffer for such OSC operations.

**Comment by ojroques** [comment]
It seems an issue from Konsole indeed. I'm closing the issue for now, feel free to re-open it if it turns out it's the plugin's fault.
