### ISSUE TITLE
dooes not work on WSL1 config tips?

### ISSUE THREAD

**Issue by matu3ba** [ojroques/nvim-osc52#15]
Unfortunately the official neovim docs suggest to use win32yank, but for me at least this does not work https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl and win32yank looks super buggy.

What setup can you recommend instead? Using powershell + `Get-Clipboard`/`Set-Clipboard` ?

**Comment by ojroques** [comment]
You shouldn't need anything mentioned in that page. Instead:
1. Install the [Windows Terminal](https://github.com/microsoft/terminal) or any terminal that supports OSC52
2. Enable WSL on Windows
3. Install Ubuntu or the Linux distribution of your choice
4. Install Neovim inside your Linux distro
5. Install the plugin and add the mappings mentioned in the README

Now everything should work out of the box. Feel free to re-open this issue if it still doesn't work.

**Comment by matu3ba** [comment]
lol. I should have used Windows Terminal from the start and not the default installed ****.
Many thanks, it just works now.
