### ISSUE TITLE
copy_visual does not respect reselect-visual (gv)

### ISSUE THREAD

**Issue by wookayin** [ojroques/nvim-osc52#18]
When pressing `gv` (:help reselect-visual), it should reselect the copied region (visual block).

Reproduction:
```
      vim.keymap.set('v', '<leader>y', require('osc52').copy_visual)
```

- visual select some text 
- `<leader>y`  (osc52.copy_visual)
- move cursor
- gv
- The same visual region should be selected again, but it doesn't.

Some codes like the following would be needed:

```
local start = vim.fn.getpos("'<")
local end = vim.fn.getpos("'>")

-- copy OSC52...

vim.fn.setpos("'<", start)
vim.fn.setpos("'>", end)
```

**Comment by ojroques** [comment]
Thanks for the report, it should be fixed in the latest commit.

**Comment by wookayin** [comment]
Awesome, thanks!
