### ISSUE TITLE
Copying does not overwrite

### ISSUE THREAD

**Issue by mikowhyHUB** [ojroques/nvim-osc52#22]
I got a weird issue.
When using plugin on macos everything works fine, copying overwrites old copy.
But with the same terminal(kitty) with the same nvim config but on linux, copying does not overwrite itself.  New lines are added to last copy and so on. 
Any ideas how to fix this?

**Comment by ojroques** [comment]
On older versions of kitty, the developer implemented OSC52 so that new copied text are concatened to previous copied text. This decision was reverted in new versions of Kitty, so you should update kitty to the latest version and it should work fine.

**Comment by mikowhyHUB** [comment]
Thank you, problem solved!
