### ISSUE TITLE
failed to copy text with mouse after using nvim-osc52 inside the tmux in kitty

### ISSUE THREAD

**Issue by ch4xer** [ojroques/nvim-osc52#28]
Reproduction steps:
1. launch kitty, run tmux locally.
2. inside tmux, select text A using mouse, and paste with `ctrl-shift-v`, which output text A as expect
3. inside tmux, launch a pane, open nvim with nvim-osc52 installed and edit a file
4. copy text B in neovim with `yy`
5. paste in another pane in tmux, which works well
6. select text A using mouse again, and paste with `ctrl-shift-v`, which output text B
7. change kitty to other terminals like alacritty, repeat steps 1-6, the problem disappears.
8. launch kitty, ssh to remote server and run tmux, repeat steps 1-6, the problem also disappears.

Minimal Configuration:

tmux
```
set -ga terminal-overrides ",xterm*:Tc"
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
set-environment -g COLORTERM "truecolor"
set -s set-clipboard on
set -g mouse on
```

kitty: default configuration

nvim-osc52 configuration:
```
require('osc52').setup {
    max_length       = 0,    -- Maximum length of selection (0 for no limit)
    silent           = true, -- Disable message on successful copy
    trim             = true, -- Trim surrounding whitespaces before copy
    tmux_passthrough = true, -- Copy from tmux into vim
}
```

I'm very confused about this issue, since if I running the following osc52 command in tmux and kitty, the problem won't happened:

```
esc="\033]52;c;$(base64 <<< 'hello world')\a"
esc="\033Ptmux;\033$esc\033\\" # tmux needs sequence escapement
printf "$esc"
```

Finally, thanks for your plugin which improves my remote development experience.

**Comment by ch4xer** [comment]
Close the issue as this is kitty's problem

**Comment by rag-hav** [comment]
How did you fix it? @ch4xer. Kitty apparantly needs an invalid osc command to clear buffer.
