### ISSUE TITLE
Can I paste from local system clipboard to remote neovim by "p"?

### ISSUE THREAD

**Issue by MichaelC001** [ojroques/nvim-osc52#29]
This plugin is amazing!

Mac is my remote computer at Home, I use windows PC in office to access Mac over SSH
How can I psate from  Windows PC clipboard to Mac neovim with key "p" over SSH？
Thank you

My Mac OS config with lazy.nvim:
```
return {
  {
    "ojroques/nvim-osc52",
    config = function()
      --vim.keymap.set("n", "<leader>c", require("osc52").copy_operator, { expr = true })
      --vim.keymap.set("n", "yy", "<leader>c_", { remap = true })
      --vim.keymap.set("v", "y", require("osc52").copy_visual)
      require("osc52").setup({
        silent = true,
      })
      function copy()
        if vim.v.event.operator == "y" and vim.v.event.regname == "+" then
          require("osc52").copy_register("+")
        end
      end
      vim.api.nvim_create_autocmd("TextYankPost", { callback = copy })
      local function copy(lines, _)
        require("osc52").copy(table.concat(lines, "\n"))
      end

      local function paste()
        return { vim.fn.split(vim.fn.getreg(""), "\n"), vim.fn.getregtype("") }
      end

      vim.g.clipboard = {
        name = "osc52",
        copy = { ["+"] = copy, ["*"] = copy },
        paste = { ["+"] = paste, ["*"] = paste },
      }
      -- Now the '+' register will copy to system clipboard using OSC52
      vim.keymap.set("n", "<leader>c", '"+y')
      vim.keymap.set("n", "<leader>cc", '"+yy')
    end,
  },
}

```

**Comment by ojroques** [comment]
Glad you like the plugin :)

There is currently no support for pasting from the clipboard with this plugin.

But most terminal emulator don't support applications reading the clipboard for obvious privacy reasons anyway.

See also https://github.com/ojroques/nvim-osc52/issues/13.

**Comment by MichaelC001** [comment]
https://github.com/EtiamNullam/deferred-clipboard.nvim
with this plugin I can copy and paste with tmux locally, but not working in SSH

**Comment by cnt0** [comment]
from my understanding it should be possible. I'm experimenting with ssh session, opened in macOS kitty terminal.

OSC52 spec defines paste command, that's how to use it:

```bash
$ echo Hello! | pbcopy # in macOS
$ printf '\e]52;c;?\007' # in ssh
52;c;SGVsbG8hCg==
$ echo SGVsbG8hCg== | base64 -d # in ssh
Hello!
```

PS OK nevermind, I'm reading https://github.com/ojroques/nvim-osc52/issues/13
