### ISSUE TITLE
Cannot copy more than 700 characters.

### ISSUE THREAD

**Issue by lkhphuc** [ojroques/nvim-osc52#3]
When I select around 800 characters, it just hang, clipboard is emptied and no-response window. I have to move a to different windows and back to get the window to be responsive again.
```
  use {'ojroques/nvim-osc52',
    config = function ()
      local function copy(lines, _)
        require('osc52').copy(table.concat(lines, '\n'))
      end
      local function paste()
        return {vim.fn.split(vim.fn.getreg(''), '\n'), vim.fn.getregtype('')}
      end
      vim.g.clipboard = {
        name = 'osc52',
        copy = {['+'] = copy, ['*'] = copy},
        paste = {['+'] = paste, ['*'] = paste},
      }
      -- Now the '+' register will copy to system clipboard using OSC52
    end
  }
```

No problem whatsoever with the old vimscript plugin though.
```
  use {"ojroques/vim-oscyank", 
  config = function()
    vim.cmd [[ autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is '+' | execute 'OSCYankReg +' | endif ]]
  end }
```

**Comment by ojroques** [comment]
Weird, I cannot reproduce. What OS and terminal emulator are you using?

**Comment by lkhphuc** [comment]
I'm using MacOS with kitty.
Edit: Tested with MacOS + Wezterm and there was no problem.

**Comment by ojroques** [comment]
Maybe try setting the [clipboard_control](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.clipboard_control) and [clipboard_max_size](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.clipboard_max_size) options in kitty:

```
clipboard_control write-clipboard write-primary
clipboard_max_size 0
```

**Comment by lkhphuc** [comment]
I tried `clipboard_max_size 0` but it doesn't help, given the default size is already 64MB. I use the same kitty setup with your old vim-osc52 without any problem.

**Comment by ojroques** [comment]
Can you share your kitty version? I'll test on my side.

**Comment by lkhphuc** [comment]
I'm runing the latest version https://github.com/kovidgoyal/kitty/releases/tag/v0.25.2

**Comment by ojroques** [comment]
I managed to reproduce your issue on Kitty. I think I've fixed it now. It seems there was an upper limit on the number of characters we can send through the 'chansend' function. Feel free to re-open the issue if your problem persists.
