### ISSUE TITLE
Example configuration behaves unexpectedly (LazyVim)

### ISSUE THREAD

**Issue by ninbura** [ojroques/nvim-osc52#30]
Using LazyVim via this configuration:
```lua
return {
  "ojroques/nvim-osc52",
  keys = {
    {
      "<leader>y",
      function() require("osc52").copy_operator() end,
      expr = true,
      desc = "copy selection to system clipboard (normal mode)"
    },
    {
      "<leader>Y",
      "<leader>c_",
      remap = true,
      desc = "copy current line into system clipboard (normal mode)"
    },
    {
      mode = "v",
      "<leader>y",
      function() require("osc52").copy_visual() end,
      desc = "copy selection to system clipboard (visual mode)"
    }
  }
}
```

- Using `<leader>y` in normal mode appears to do nothing. ❌
- Using `<leader>Y` deletes the current line, and puts me into insert mode. ❌
- Using `<leader>y` in visual mode works as expected, text is yanked to my system clipboard via `osc52` and a message is printed confirming that. ✅

Maybe I don't understand the purpose of `<leader>y` → `require("osc52").copy_operator()` mapping in normal mode, but as mentioned I see no effect. `<leader>Y` → `<leader>c_` in normal mode is most definitely not copying the currently highlighted line; as I assume that mapping would, given the example configuration's descriptions:
```lua
vim.keymap.set('n', '<leader>c', require('osc52').copy_operator, {expr = true})
vim.keymap.set('n', '<leader>cc', '<leader>c_', {remap = true})
vim.keymap.set('v', '<leader>c', require('osc52').copy_visual)
```
> In normal mode, <leader>c is an operator that will copy the given text to the clipboard.
>  In normal mode, <leader>cc will copy the current line.
>  In visual mode, <leader>c will copy the current selection.

The second map (normal mode `<leader>y`) is doing something, just the wrong thing. Changing the second value, or what the map is being remapped to changes the behavior. I say this because that means that my syntax / configuration is correct in the sense that something is happening, just not the right something. And as previously mentioned, the visual mode mapping works as expected. Using native remapping has an identical effect to the LazyVim syntax remapping.
```lua
vim.keymap.set("n", "<leader>Y", "<leader>c_", { remap = true, desc = "copy current line to system clipboard (normal mode)" })
```

I'm skeptical of replacing my clipboard provider entirely with `osc52` as I run the potential risk of using a terminal that doesn't provide `osc52` support, and losing access to basic clipboard functionality. So, I'd love to get this working without resorting to that.

**Comment by ojroques** [comment]
Hello,

About your second mapping, it should be:
```lua
 {
      "<leader>Y",
      "<leader>y_",
      remap = true,
      desc = "copy current line into system clipboard (normal mode)"
},
```
basically, `<leader>Y` will call `<leader>y_`, which will be replaced with your first mapping (because `remap = true`) with the operator `_` which selects the entire line.

But it will work only if your first mapping works if the first place. Does the first mapping works with:
```lua
{
      mode = "n",
      "<leader>y",
      require('osc52').copy_operator,
      expr = true,
      desc = "copy selection to system clipboard (normal mode)"
},
```

**Comment by ninbura** [comment]
Oh, duh, I see how that's supposed to work now at the very least 🤦‍♂️

However, even when I change that second mapping to what it should be, nothing's happening.
```lua
return {
  "ojroques/nvim-osc52",
  keys = {
    {
      mode = "n",
      "<leader>y",
      function() require("osc52").copy_operator() end,
      expr = true,
      desc = "copy selection to system clipboard (normal mode)"
    },
    {
      mode = "n",
      "<leader>Y",
      "<leader>y_",
      remap = true,
      desc = "copy current line into system clipboard (normal mode)"
    },
    {
      mode = "v",
      "<leader>y",
      function() require("osc52").copy_visual() end,
      desc = "copy selection to system clipboard (visual mode)"
    }
  }
}
```

So, the problem is that my first remap isn't working. The reason I put `require('osc52').copy_operator` in a function is because when I don't, I get an error loading the plugin via lazy.
```
Error detected while processing C:\Users\gabri\AppData\Local\nvim\init.lua:
Failed to load `plugins.osc52`

C:/Users/gabri/AppData/Local/nvim/lua/plugins/osc52.lua:7: module 'osc52' not found:
^Ino field package.preload['osc52']
cache_loader: module osc52 not found
cache_loader_lib: module osc52 not found
^Ino file '.\osc52.lua'
^Ino file 'C:\Program Files\Neovim\bin\lua\osc52.lua'
^Ino file 'C:\Program Files\Neovim\bin\lua\osc52\init.lua'
^Ino file '.\osc52.dll'
^Ino file 'C:\Program Files\Neovim\bin\osc52.dll'
^Ino file 'C:\Program Files\Neovim\bin\loadall.dll'

# stacktrace:
  - lua/plugins/osc52.lua:7
  - lua/lazy_init.lua:16
  - init.lua:3
```

I'd think it'd work with the function syntax since the third mapping does... I wonder if it has anything to do with the `expr` bit. Not sure what that is. Apologies for any negligence, I've been using NeoVim for only about a week.

**Comment by ninbura** [comment]
If I change `<leader>y_` to `y_` in the second bind, `<leader>Y` copies the current line within NeoVim. So, that second keybind is mapping to what I'm telling it to, and the `_` does grab the line with the internal copy.

It's just that that first mapping doesn't work.

**Comment by ninbura** [comment]
I was about to post a discussion on the [LazyVim repository](https://github.com/LazyVim/LazyVim), but I found that [someone had already asked](https://github.com/LazyVim/LazyVim/discussions/1883).

I don't understand why, but you have to `return` the `copy_operator` call:
```lua
return {
  "ojroques/nvim-osc52",
  keys = {
    {
      "<leader>y",
      function() return require("osc52").copy_operator() end, -- <-- previously I wasn't using a return statement here
      desc = "copy selection to system clipboard (normal mode)",
      expr = true
    },
    {
      "<leader>Y",
      "<leader>y_",
      remap = true,
      desc = "copy current line into system clipboard (normal mode)"
    },
    {
      mode = "v",
      "<leader>y",
      function() require("osc52").copy_visual() end,
      desc = "copy selection to system clipboard (visual mode)"
    }
  }
}
```
Finally got it fully working via the above configuration without resorting to usage of native lua key-mapping.

**Comment by nguyenvulong** [comment]
@ninbura thank you for your sample code, I was able to remove the `return` statement and modified the config as follows; and it works flawlessly.
Previously I tried to use my own `osc52-copy` binary but was not successfuly to make it work with LazyVim. Thank you @ojroques for a great repo.

```nvim
return {
  "ojroques/nvim-osc52",
  keys = {
    {
      "<leader>y",
      function()
        require("osc52").copy_operator()
      end,
      desc = "copy selection to system clipboard (normal mode)",
      expr = true,
      mode = "n",
    },
    {
      "<leader>y",
      function()
        require("osc52").copy_visual()
      end,
      desc = "copy selection to system clipboard (visual mode)",
      mode = "v",
    },
  },
}
```
