### ISSUE TITLE
Config cannot be applied on neovim 0.9 or instructions are unclear

### ISSUE THREAD

**Issue by AkechiShiro** [ojroques/nvim-osc52#32]
Hello,

the configuration examples given all fails to be applied in init.vim as their syntax looks like they are lua pieces of codes and not vimscript syntax.

Is there any instructions that are missing from the readme to actually make this config work ?

**Comment by AkechiShiro** [comment]
Yep found out it was indeed lua configuration.

I've imported the configuration successfully but the require seems to fail : 
```
Error detected while processing /home/licht/.config/nvim/init.vim:                                                                           
line  131:                                                                                                                                   
E5108: Error executing lua [string ":lua"]:1: module 'osc52' not found:                                                                      
        no field package.preload['osc52']                                                                                                    
        no file '/nix/store/k85k151qrrl98gfbj5z00h36a5kj4fwy-luajit-2.1.1693350652-env/share/lua/5.1/osc52.lua'                              
        no file '/nix/store/k85k151qrrl98gfbj5z00h36a5kj4fwy-luajit-2.1.1693350652-env/share/lua/5.1/osc52/init.lua'                         
        no file '/nix/store/k85k151qrrl98gfbj5z00h36a5kj4fwy-luajit-2.1.1693350652-env/lib/lua/5.1/osc52.so'                                 
stack traceback:                                                                                                                             
        [C]: in function 'require'                                                                                                           
        [string ":lua"]:1: in main chunk  
```

Not sure why it is looking up the lua script at this exact path, since the plugin is managed by Plug and inside  `$HOME/.local/share/nvim`

**Comment by AkechiShiro** [comment]
I suggest adding to the readme the following doc : https://neovim.io/doc/user/lua-guide.html 

As well as clearly stating it is **lua** configuration and not **vimscript** as this is ambiguous right now and seems to be left as an exercise for the reader.

**Comment by AkechiShiro** [comment]
Will reopen until I can fix it or it gets fixed.

**Comment by ojroques** [comment]
Hello,

I won't add Vimscript in the README as I'm assuming that users of Neovim and this plugin are familiar with Lua.

But you might be interested in https://github.com/ojroques/vim-oscyank, which does the exact same job as nvim-osc52 but for Vim. You'll find Vimscript instructions there as well.
