### ISSUE TITLE
how to use nvim default osc52 provider?

### ISSUE THREAD

**Issue by Kreijstal** [ojroques/nvim-osc52#34]
It has been non trivially hard for me

**Comment by ojroques** [comment]
Hello!

You have the full documentation in Neovim directly. See `:h clipboard-osc52` to have a full explanation. Note that this works only in Neovim nightly. You should uninstall this plugin first though.

**Comment by Kreijstal** [comment]
My distro doesn't ship nvim nightly, I think I'll have to use this plug-in instead and if that doesn't work I'll just use the vim plugin that still works

**Comment by Kreijstal** [comment]
> Hello!
> 
> You have the full documentation in Neovim directly. See `:h clipboard-osc52` to have a full explanation. Note that this works only in Neovim nightly. You should uninstall this plugin first though.

the explanation in :h just gives you code but not where to put it, btw.
