### ISSUE TITLE
neovim 0.10.1 setting force the OSC clipboard doesn't work

### ISSUE THREAD

**Issue by ipstone** [ojroques/nvim-osc52#40]
hello,
 
I tried to add this to my nvim settings:
```
    vim.g.clipboard = {
      name = 'OSC 52',
      copy = {
        ['+'] = require('vim.ui.clipboard.osc52').copy('+'),
        ['*'] = require('vim.ui.clipboard.osc52').copy('*'),
      },
      paste = {
        ['+'] = require('vim.ui.clipboard.osc52').paste('+'),
        ['*'] = require('vim.ui.clipboard.osc52').paste('*'),
      },
    }
```

But it doesn't seem being able to copy to system's clipboard ... I am using iTerm2, tmux 3.4.

Thoughts?

thanks!

**Comment by ojroques** [comment]
Hello,

You are using the built-in OSC52 provider which is not related to this plugin. Check the manual to configure it: `:help clipboard-osc52`.
