### ISSUE TITLE
osc52 does not copy to tmux clipboard

### ISSUE THREAD

**Issue by miversen33** [ojroques/nvim-osc52#6]
Hello! I am having an odd issue in that I cannot seem to get osc52 to copy to tmux's system clipboard. I have verified that the tmux clipboard _does_ work as I can copy things from neovim with tmux itself, but that is obviously painful.

[I am using the default config in the readme](https://github.com/ojroques/nvim-osc52#configuration)
```lua
require('osc52').setup {
  max_length = 0,  -- Maximum length of selection (0 for no limit)
  silent = false,  -- Disable message on successful copy
  trim = false,    -- Trim text before copy
}

local function copy(lines, _)
  require('osc52').copy(table.concat(lines, '\n'))
end

local function paste()
  return {vim.fn.split(vim.fn.getreg(''), '\n'), vim.fn.getregtype('')}
end

vim.g.clipboard = {
  name = 'osc52',
  copy = {['+'] = copy, ['*'] = copy},
  paste = {['+'] = paste, ['*'] = paste},
}

-- Now the '+' register will copy to system clipboard using OSC52
vim.keymap.set('n', '<leader>c', '"+y')
vim.keymap.set('n', '<leader>cc', '"+yy')
```

Specifically, my config can be found [here](https://github.com/miversen33/miversen-dotfiles/blob/bcc84bcf4f047461ac21f252b70c32860f8ff5a1/editors/nvim/lua/plugins.lua#L731-L767)

**Comment by ojroques** [comment]
Hello, have you tried these steps first to enable osc52 in tmux?

https://github.com/tmux/tmux/wiki/Clipboard#quick-summary

Also what is your tmux version?

**Comment by miversen33** [comment]
Below is the details from my tmux details. I have previously used [oscyank](https://github.com/ojroques/vim-oscyank) and had no issues, but I seem to be running into some weirdness in migrating to osc52 :/

```
$ tmux show -s set-clipboard
set-clipboard external

$ tmux info | grep Ms
180: Ms: (string) \033]52;%p1%s;%p2%s\a

$ echo $TERM
xterm-256color

$ tmux -V
tmux 3.0a
```

**Comment by miversen33** [comment]
To add to this, I can also confirm that the above configuration works fine if I am _not_ running tmux.

Fine being, I can yank and it goes to my system clipboard. So this appears to be localized within how osc52 is talking to tmux

**Comment by ojroques** [comment]
I managed to reproduce your issue. It seems that `external` does not work, instead use:
```sh
set -s set-clipboard on
```

Here's a post explaining why `on` works but not `external`: https://unix.stackexchange.com/questions/560428/what-is-the-difference-between-the-values-off-and-external-for-the-set-clip.

Feel free to reopen the issue if your problem persists :)

**Comment by miversen33** [comment]
Thats really weird. I can confirm that `on` fixed the issue. I wonder, any idea why `external` worked with [oscyank](https://github.com/ojroques/vim-oscyank) but not with nvim-osc52?

**Comment by ojroques** [comment]
It's because vim-oscyank handled tmux differently than other terminals to support old versions of tmux also. This plugin treats it the same as others but therefore is not compatible with older versions.

**Comment by miversen33** [comment]
Ahh that makes sense. You're awesome, I appreciate you :)

**Comment by lherman-cs** [comment]
I have the same issue, but setting tmux clipboard to `on` doesn't fix the problem.

```
$ tmux show -s set-clipboard
set-clipboard on

$ tmux info | grep Ms
192: Ms: (string) \033]52;%p1%s;%p2%s\a

$ echo $TERM
xterm-256color

$ tmux -V
tmux 3.3a

```

**Comment by lherman-cs** [comment]
@ojroques

**Comment by ojroques** [comment]
What terminal are you using? Do you know if it supports the OSC52 sequence?

**Comment by lherman-cs** [comment]
I'm using Alacritty. I have solved the issue, I need to add this to my .tmux.conf, `set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"`.

Thanks for the plugin ^^

**Comment by SonglinLife** [comment]
I encountered the same problem. Thanks to this issue, I simply used "set -s set-clipboard on" and solve it. :pray:
