### ISSUE TITLE
osc52.copy always writes to /dev/fd/2 because vim.fn.filewritable always succeeds, even when the file does not exist

### ISSUE THREAD

**Issue by bruxisma** [ojroques/nvim-osc52#9]
Hello!

Thanks for writing this plugin! Unfortunately, I am connecting to a Windows machine via SSH and the `osc52.copy` function will fail every time because `vim.fn.filewritable` does not return a boolean but instead returns `0`. In lua, only `nil` and `false` are actually `false`

That said, I can say the `else` block does work correctly if a small patch is applied:

```lua
  if vim.fn.filewritable('/dev/fd/2') ~= 0 then
```

I've applied this and some more experimental stuff (like using the builtin function `vim.notify` for errors/status messages) so I couldn't just open a PR directly to fix this, as I've hacked this plugin up quiet a bit on my end 😅

**Comment by ojroques** [comment]
Fixed. Thanks!
